import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { itineraryId } = body

    if (!itineraryId) {
      return NextResponse.json(
        { error: 'Itinerary ID is required' },
        { status: 400 }
      )
    }

    const itinerary = await prisma.itinerary.findUnique({
      where: { id: itineraryId }
    })

    if (!itinerary) {
      return NextResponse.json(
        { error: 'Itinerary not found' },
        { status: 404 }
      )
    }

    // Generate Markdown content
    const markdown = `# ${itinerary.destination} Itinerary

**Dates:** ${itinerary.startDate.toLocaleDateString()} - ${itinerary.endDate.toLocaleDateString()}
**Budget:** ${itinerary.budget}
**Travelers:** ${itinerary.travelers}
**Pace:** ${itinerary.pace}

${itinerary.content}

---
*Generated by AI Travel Guide*
`

    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="${itinerary.destination}-itinerary.md"`
      }
    })

  } catch (error) {
    console.error('Export Error:', error)
    return NextResponse.json(
      { error: 'Failed to export itinerary' },
      { status: 500 }
    )
  }
}
